extends: airbnb-base
env:
  node: true
  mocha: true
  es6: true
parser: typescript-eslint-parser
parserOptions:
  sourceType: module
  ecmaFeatures:
    modules: true
rules:
  no-undef: off
  import/extensions: off
  import/no-unresolved: off
